### ISSUE TITLE
Celery Worker Resources

### ISSUE THREAD

**Issue by james-otten** [nycmeshnet/meshdb#893]
Right now the following is applied to both containers, but it only really needs this for `celery-worker`

```
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
```
